### ISSUE TITLE
how come only your shared build working

### ISSUE THREAD

**Issue by pasumarthivijaykumar** [keckelt/openjdk11-alpine#2]
i got a download from https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz

and other from docker file mentioned.

the one which downloaded from java.net does not recognized in Alpine:latest hence i always get java: not found
but your build works fine. Any points to share with me here? Thanks.

**Comment by keckelt** [comment]
Hi @pasumarthivijaykumar ,
sorry that I missed your issue.

You need a build specifically for Alpine Linux. These were, but no longer are provided at java.net for Java11 ([Java12](https://download.java.net/java/early_access/alpine/30/binaries/openjdk-12-ea+30_linux-x64-musl_bin.tar.gz) and [Java13](https://jdk.java.net/13/) are still online).

I extracted the JDK from one of my containers and [uploaded it](http://drive.jku.at/ssf/s/readFile/share/8207/4867522971216226929/publicLink/openjdk-11-GA_linux-x64-musl_bin.tar.gz
), as I could not find any other legit source.

**Comment by keckelt** [comment]
You can also check out [Project Portola](http://openjdk.java.net/projects/portola/) and [this issue over at openjdk](https://github.com/docker-library/openjdk/issues/211#issuecomment-426641655).
