### ISSUE TITLE
OpenJDK 11.0.2 is GA

### ISSUE THREAD

**Issue by bchanan03** [keckelt/openjdk11-alpine#3]
Hi All,

OpenJDK 11.0.2 went GA - means its production ready. Can anyone create alpine based image.
Thanks

**Comment by bratkartoffel** [comment]
OpenJDK11 is finally in Alpine, starting with 3.10:
https://pkgs.alpinelinux.org/packages?name=openjdk11*&branch=v3.10&arch=x86_64

So you can create your own container and simply ```apk add``` the package.
